@startuml
skinparam rectangle<<behavior>> {
	roundCorner 25
}
sprite $component jar:archimate/component

rectangle ContentExchanger <<$component>><<behavior>>
rectangle MessageExchanger <<$component>><<behavior>>
rectangle NodeFinder <<$component>><<behavior>>
rectangle PublishContentStorage <<$component>><<behavior>>
rectangle WantContentStorage <<$component>><<behavior>>
rectangle PublishMessageStorage <<$component>><<behavior>>
rectangle WantMessageStorage <<$component>><<behavior>>

rectangle ConnectionController <<$component>><<behavior>>
rectangle ObjectStore <<$component>><<behavior>>

ContentExchanger -down-> NodeFinder
ContentExchanger -down-> ConnectionController
ContentExchanger -down-> PublishContentStorage
ContentExchanger -down-> WantContentStorage

MessageExchanger -down-> ConnectionController
MessageExchanger -down-> NodeFinder
MessageExchanger -down-> PublishMessageStorage
MessageExchanger -down-> WantMessageStorage

NodeFinder -down-> ConnectionController
NodeFinder -down-> PublishMessageStorage
NodeFinder -down-> WantMessageStorage
NodeFinder -down-> PublishContentStorage
NodeFinder -down-> WantContentStorage

PublishMessageStorage -down-> ObjectStore
WantMessageStorage -down-> ObjectStore
PublishContentStorage -down-> ObjectStore
WantContentStorage -down-> ObjectStore

@enduml
