@startuml sequence

participant Browser as browser
participant api
participant batch
participant S3 as s3
database DB as db

browser -> api : request upload url
api -> db : insert job
api -> api : gen upload url
api --> browser : upload url
browser -> s3 : post file to upload url
s3 -> batch : send completed event
batch -> s3 : request uploaded file
s3 --> batch : uploaded file
batch -> batch : convert file
batch -> s3 : upload converted file
batch -> db : update job

loop watch job
    api -> db : read job
    db --> api : job
    par success pull message
        api -> api : gen converted file url
        api --> browser : converted file url

        browser -> s3 : request converted file
        s3 --> browser : converted file
    end
end

@enduml
